# Generated by Django 4.2.2 on 2023-06-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='userName', max_length=32, null=True)),
                ('userpass', models.CharField(blank=True, db_column='userPass', max_length=32, null=True)),
                ('userpicture', models.TextField(blank=True, db_column='userPicture', null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(db_column='messageID', primary_key=True, serialize=False)),
                ('messagecontent', models.CharField(blank=True, db_column='messageContent', max_length=512, null=True)),
                ('messageattachments', models.TextField(blank=True, db_column='MessageAttachments', null=True)),
                ('messagesender', models.ForeignKey(db_column='messageSender', on_delete=django.db.models.deletion.DO_NOTHING, to='chat.user')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
